name: Integrated tests

on:
  push:

jobs:
  test:
    name: Build Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run:  meson setup builddir |
              ninja -C builddir
      - name: Run
        run: GST_PLUGIN_PATH=builddir/gst-plugin/ ./builddir/gst-plugin/gstgzdec_test ./COPYING.LIB
